"""empty message

Revision ID: 556f657d2e8c
Revises: 
Create Date: 2024-02-13 13:41:15.761186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '556f657d2e8c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_banglish_name', table_name='books')
    op.drop_index('ix_books_name', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sku', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('banglish_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('short_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('regular_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sale_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('manage_stock', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('in_stock', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('shipping_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('edition', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cover', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('images', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('condition', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('isbn', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('no_of_pages', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('featured', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('must_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_vintage', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_islamic', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_translated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_recommended', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('big_sale', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('stock_location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shelf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('row_col', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bar_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('selector', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='books_pkey'),
    sa.UniqueConstraint('sku', name='books_sku_key')
    )
    op.create_index('ix_books_name', 'books', ['name'], unique=False)
    op.create_index('ix_books_banglish_name', 'books', ['banglish_name'], unique=False)
    # ### end Alembic commands ###
