"""baseline_migration

Revision ID: 997de0cfedb2
Revises: 
Create Date: 2024-10-10 22:22:01.650931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '997de0cfedb2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'folder',
               existing_type=postgresql.ENUM('book', 'author', 'category', 'publisher', 'profile_picture', 'review', 'dummy', 'payment_gateway', name='imagefolder'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('images', 'public_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('public_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('images', 'folder',
               existing_type=sa.String(),
               type_=postgresql.ENUM('book', 'author', 'category', 'publisher', 'profile_picture', 'review', 'dummy', 'payment_gateway', name='imagefolder'),
               existing_nullable=False)
    # ### end Alembic commands ###
