"""baseline migration

Revision ID: e92e30026256
Revises: 
Create Date: 2024-10-09 17:36:29.071828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92e30026256'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coupon_user_link')
    op.drop_table('order_coupon_link')
    op.create_unique_constraint(None, 'addresses', ['id'])
    op.create_unique_constraint(None, 'authors', ['id'])
    op.create_unique_constraint(None, 'books', ['id'])
    op.create_unique_constraint(None, 'categories', ['id'])
    op.create_unique_constraint(None, 'coupons', ['id'])
    op.create_unique_constraint(None, 'couriers', ['id'])
    op.create_unique_constraint(None, 'images', ['id'])
    op.create_unique_constraint(None, 'order_status', ['id'])
    op.create_unique_constraint(None, 'orders', ['id'])
    op.create_unique_constraint(None, 'payment_gateways', ['id'])
    op.create_unique_constraint(None, 'publishers', ['id'])
    op.create_unique_constraint(None, 'reviews', ['id'])
    op.create_unique_constraint(None, 'settings', ['id'])
    op.create_unique_constraint(None, 'tags', ['id'])
    op.create_unique_constraint(None, 'transactions', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_constraint(None, 'settings', type_='unique')
    op.drop_constraint(None, 'reviews', type_='unique')
    op.drop_constraint(None, 'publishers', type_='unique')
    op.drop_constraint(None, 'payment_gateways', type_='unique')
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'order_status', type_='unique')
    op.drop_constraint(None, 'images', type_='unique')
    op.drop_constraint(None, 'couriers', type_='unique')
    op.drop_constraint(None, 'coupons', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_constraint(None, 'authors', type_='unique')
    op.drop_constraint(None, 'addresses', type_='unique')
    op.create_table('order_coupon_link',
    sa.Column('order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('coupon_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name='order_coupon_link_coupon_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_coupon_link_order_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', 'coupon_id', name='order_coupon_link_pkey')
    )
    op.create_table('coupon_user_link',
    sa.Column('coupon_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name='coupon_user_link_coupon_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='coupon_user_link_user_id_fkey'),
    sa.PrimaryKeyConstraint('coupon_id', 'user_id', name='coupon_user_link_pkey')
    )
    # ### end Alembic commands ###
