from enum import Enum


class City(str, Enum):
    bagerhat = 'bagerhat'
    bandarban = 'bandarban'
    barguna = 'barguna'
    barisal = 'barisal'
    bhola = 'bhola'
    bogura = 'bogura'
    brahmanbaria = 'brahmanbaria'
    chandpur = 'chandpur'
    chapainawabganj = 'chapainawabganj'
    chattogram = 'chattogram'
    chuadanga = 'chuadanga'
    comilla = 'comilla'
    coxbazar = 'coxbazar'
    dhaka = 'dhaka'
    dinajpur = 'dinajpur'
    faridpur = 'faridpur'
    feni = 'feni'
    gaibandha = 'gaibandha'
    gazipur = 'gazipur'
    gopalganj = 'gopalganj'
    habiganj = 'habiganj'
    jamalpur = 'jamalpur'
    jashore = 'jashore'
    jhalokathi = 'jhalokathi'
    jhenaidah = 'jhenaidah'
    joypurhat = 'joypurhat'
    khagrachari = 'khagrachari'
    khulna = 'khulna'
    kishoreganj = 'kishoreganj'
    kurigram = 'kurigram'
    kushtia = 'kushtia'
    lakshmipur = 'lakshmipur'
    lalmonirhat = 'lalmonirhat'
    madaripur = 'madaripur'
    magura = 'magura'
    manikganj = 'manikganj'
    meherpur = 'meherpur'
    moulvibazar = 'moulvibazar'
    munshiganj = 'munshiganj'
    mymensingh = 'mymensingh'
    naogaon = 'naogaon'
    narail = 'narail'
    narayanganj = 'narayanganj'
    narsingdi = 'narsingdi'
    natore = 'natore'
    netrokona = 'netrokona'
    nilphamari = 'nilphamari'
    noakhali = 'noakhali'
    pabna = 'pabna'
    panchagarh = 'panchagarh'
    patuakhali = 'patuakhali'
    pirojpur = 'pirojpur'
    rajbari = 'rajbari'
    rajshahi = 'rajshahi'
    rangamati = 'rangamati'
    rangpur = 'rangpur'
    satkhira = 'satkhira'
    shariatpur = 'shariatpur'
    sherpur = 'sherpur'
    sirajganj = 'sirajganj'
    sunamganj = 'sunamganj'
    sylhet = 'sylhet'
    tangail = 'tangail'
    thakurgaon = 'thakurgaon'

    @classmethod
    def values(cls):
        return [city.value for city in cls]
